// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  describe('Controller: LogoutCtrl', function() {
    var LogoutCtrl, scope;
    beforeEach(module('moneyApp'));
    LogoutCtrl = void 0;
    scope = void 0;
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return LogoutCtrl = $controller('LogoutCtrl', {
        $scope: scope
      });
    }));
    return it('should ...', function() {
      return expect(1).toEqual(1);
    });
  });

}).call(this);

//# sourceMappingURL=logout.controller.spec.js.map
