// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  angular.module('moneyApp').config(function($stateProvider) {
    return $stateProvider.state('logout', {
      url: '/logout',
      templateUrl: 'app/logout/logout.html',
      controller: 'LogoutCtrl'
    });
  });

}).call(this);

//# sourceMappingURL=logout.js.map
