// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  describe('Controller: ForgotPasswordCtrl', function() {
    var ForgotPasswordCtrl, scope;
    beforeEach(module('moneyApp'));
    ForgotPasswordCtrl = void 0;
    scope = void 0;
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return ForgotPasswordCtrl = $controller('ForgotPasswordCtrl', {
        $scope: scope
      });
    }));
    return it('should ...', function() {
      return expect(1).toEqual(1);
    });
  });

}).call(this);

//# sourceMappingURL=forgot-password.controller.spec.js.map
