// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  angular.module('moneyApp').factory('ExceptionLog', function($log, $window) {
    var error, tag;
    tag = 'ExceptionLog.service';
    $log.info(tag);
    error = function(exception, cause) {
      $log.error.apply($log, arguments);
      try {
        $.ajax({
          type: 'POST',
          url: '/api/logs',
          data: {
            log: angular.toJson({
              url: $window.location.href,
              message: exception.toString,
              type: 'EXCEPTION',
              stackTrace: printStackTrace({
                e: exception
              }),
              cause: cause || ''
            })
          }
        });
        return $log.info(tag, 'Logged exception to server-side');
      } catch (_error) {
        $log.warn(tag, 'Error server-side logging failed');
        return $log.warn(tag, _error);
      }
    };
    return (function() {
      return error;
    })();
  });

  angular.module('moneyApp').provider('$exceptionHandler', {
    $get: function(ExceptionLog) {
      return ExceptionLog;
    }
  });

}).call(this);

//# sourceMappingURL=ExceptionLog.service.js.map
