// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  angular.module('moneyApp').config(function($stateProvider) {
    return $stateProvider.state('login', {
      url: '/login',
      templateUrl: 'app/login/login.html',
      controller: 'LoginCtrl'
    });
  });

}).call(this);

//# sourceMappingURL=login.js.map
