// Generated by CoffeeScript 1.9.2
(function() {
  'use strict';
  describe('Controller: LoginCtrl', function() {
    var LoginCtrl, scope;
    beforeEach(module('moneyApp'));
    LoginCtrl = void 0;
    scope = void 0;
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return LoginCtrl = $controller('LoginCtrl', {
        $scope: scope
      });
    }));
    return it('should ...', function() {
      return expect(1).toEqual(1);
    });
  });

}).call(this);

//# sourceMappingURL=login.controller.spec.js.map
